/**
 * Test harness: expose module APIs on globalThis.LRPH for vm-based unit tests.
 */
import "../src/page-hook";
import { debugEnabled, log } from "../src/debug";
import { isFrameScheduled, frameTickerCount, teardownFrame } from "../src/frame";
import { matchPhrase } from "../src/matcher";
import { clearGlossPanels, ensureToolbarButton, fillGlossPanel, GLOSS_ICON_PATH, EMPTY_GLOSS_ICON_PATH, sidebarOpenFromStored, SIDEBAR_OPEN_KEY, glossObserverActive, isGlossPanelNode, isGlossPanelOpen, isGlossSidebarOpen, loadGlossPanelPref, refreshGlossPanels, setGlossPanelOpen, setGlossSidebarOpen, syncGlossPanels } from "../src/panel";
import {
  compactKey,
  ingestPhrases,
  ingestPhraseKeys,
  ingestPhraseSenses,
  harvestFilledTooltips,
  findLinePhrases,
  findAllLinePhrases,
  matchPhraseOnLine,
  pickNonOverlapping,
  phraseDictSize,
  phrasePrefetchReady,
  resetPhraseDict,
  sensesForPhrase,
  glossEntriesFor,
  phraseLabelFromTokens,
  PHRASE_DICT_CAP,
} from "../src/phrases";
import {
  isPhrasePattern,
  isTtReady,
  tooltipHasDict,
  isDictSrcHeader,
  isDictSenseLine,
  multiWordHeaders,
  phraseFromTooltip,
  phraseSenseGroupsFromTooltip,
  sensesFromTooltip,
  findPhrasePopup,
  visibleFilledTooltips,
} from "../src/popup";
import {
  startRuntime,
  teardownRuntime,
  ensureRuntime,
  isRuntimeActive,
  isRuntimeObserving,
  isRuntimeProbing,
} from "../src/runtime";
import {
  SUBTITLE_ROOT_SELECTORS,
  TRANSLATION_SELECTORS,
  MAIN_VIDEO_SELECTORS,
  EMBED_PLAYER_SELECTORS,
  WORD_SEL,
  HOVER_DICT_SEL,
  isInTranslation,
  subtitleRootFor,
  isInSubtitleRoot,
  hoverDictEl,
  lineTokens,
  tokensInRoot,
  subtitleRootsWithWords,
  overlayHostFor,
  liveCueFingerprint,
  isLineToken,
  isCueToken,
  pickPlayingVideo,
  findPlayingVideo,
  findGlossSurface,
  findMainToolbar,
  isInTranscriptList,
  isPlayerCueRoot,
  isCurrentUnitRoot,
  isLearningSurface,
  rememberPointerCue,
  clearPointerCue,
  currentCueRoots,
  findReaderSentenceRoot,
  isWatchPlayerSurface,
  isNonWatchRoute,
  isWatchRoute,
  isLrSaveOrStarControl,
  pickTopRightControl,
  isTopRightPlayerControl,
  pickPlayerSurface,
  isPlayerIframe,
  MAIN_TOOLBAR_SEL,
  LR_CORNER_CONTROL_SELECTORS,
} from "../src/selectors";
import {
  collapseWs,
  normalize,
  tokenize,
  tokenEq,
  looksCjk,
  visibleSurface,
  visibleSurfaceShallow,
  rawText,
  joinDisplayTokens,
  contractionCueTokens,
  isGlueToken,
  isHyphenPunct,
  isHyphenBoundNgramStart,
  isCliticBigram,
} from "../src/text";
import { isLanguageReactorHost } from "../src/host";
import {
  disarmHoverHold,
  armHoverHold,
  HOVER_HOLD_ARMED_CLASS,
  hoverHoldCssText,
  installHoverHold,
  isHoverHoldArmed,
  pointerMovePixels,
} from "../src/hover-hold";
import {
  injectHoverHoldStyle,
  installStarHold,
  isBareSaveShortcutKey,
  isPhraseSaveAllowed,
  isPhraseSaveUrl,
  noteTrustedPhraseSaveGesture,
  shouldBlockPhraseSaveRequest,
  shouldBlockCuePointer,
  shouldBlockSaveShortcutKey,
} from "../src/star-hold";

const LRPH = {
  debugEnabled,
  log,
  collapseWs,
  normalize,
  tokenize,
  tokenEq,
  looksCjk,
  visibleSurface,
  visibleSurfaceShallow,
  rawText,
  joinDisplayTokens,
  contractionCueTokens,
  isGlueToken,
  isHyphenPunct,
  isHyphenBoundNgramStart,
  isCliticBigram,
  isLanguageReactorHost,
  SUBTITLE_ROOT_SELECTORS,
  TRANSLATION_SELECTORS,
  WORD_SEL,
  HOVER_DICT_SEL,
  isInTranslation,
  subtitleRootFor,
  isInSubtitleRoot,
  hoverDictEl,
  lineTokens,
  tokensInRoot,
  subtitleRootsWithWords,
  overlayHostFor,
  liveCueFingerprint,
  isLineToken,
  isCueToken,
  matchPhrase,
  isPhrasePattern,
  isTtReady,
  tooltipHasDict,
  isDictSrcHeader,
  isDictSenseLine,
  multiWordHeaders,
  phraseFromTooltip,
  phraseSenseGroupsFromTooltip,
  sensesFromTooltip,
  findPhrasePopup,
  visibleFilledTooltips,
  compactKey,
  ingestPhrases,
  ingestPhraseKeys,
  ingestPhraseSenses,
  harvestFilledTooltips,
  findLinePhrases,
  findAllLinePhrases,
  matchPhraseOnLine,
  pickNonOverlapping,
  phraseDictSize,
  phrasePrefetchReady,
  resetPhraseDict,
  sensesForPhrase,
  glossEntriesFor,
  phraseLabelFromTokens,
  PHRASE_DICT_CAP,
  MAIN_VIDEO_SELECTORS,
  EMBED_PLAYER_SELECTORS,
  pickPlayingVideo,
  findPlayingVideo,
  findGlossSurface,
  isInTranscriptList,
  isPlayerCueRoot,
  isCurrentUnitRoot,
  isLearningSurface,
  isWatchPlayerSurface,
  rememberPointerCue,
  clearPointerCue,
  currentCueRoots,
  findReaderSentenceRoot,
  isNonWatchRoute,
  isWatchRoute,
  isLrSaveOrStarControl,
  pickTopRightControl,
  isTopRightPlayerControl,
  pickPlayerSurface,
  isPlayerIframe,
  MAIN_TOOLBAR_SEL,
  findMainToolbar,
  LR_CORNER_CONTROL_SELECTORS,
  fillGlossPanel,
  ensureToolbarButton,
  refreshGlossPanels,
  syncGlossPanels,
  clearGlossPanels,
  isGlossPanelNode,
  isGlossPanelOpen,
  isGlossSidebarOpen,
  setGlossPanelOpen,
  setGlossSidebarOpen,
  loadGlossPanelPref,
  sidebarOpenFromStored,
  SIDEBAR_OPEN_KEY,
  GLOSS_ICON_PATH,
  EMPTY_GLOSS_ICON_PATH,
  glossObserverActive,
  isFrameScheduled,
  frameTickerCount,
  teardownFrame,
  startRuntime,
  teardownRuntime,
  ensureRuntime,
  isRuntimeActive,
  isRuntimeObserving,
  isRuntimeProbing,
  disarmHoverHold,
  armHoverHold,
  HOVER_HOLD_ARMED_CLASS,
  hoverHoldCssText,
  installHoverHold,
  isHoverHoldArmed,
  pointerMovePixels,
  shouldBlockCuePointer,
  injectHoverHoldStyle,
  installStarHold,
  isBareSaveShortcutKey,
  isPhraseSaveAllowed,
  isPhraseSaveUrl,
  noteTrustedPhraseSaveGesture,
  shouldBlockPhraseSaveRequest,
  shouldBlockSaveShortcutKey,
};

(globalThis as typeof globalThis & { LRPH: typeof LRPH }).LRPH = LRPH;
